[build]
  command = "gatsby build"
  publish = "public/"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://ninjabotdocs.netlify.com/*"
  to = "https://docs.ninjabot.site/:splat"
  status = 301
  force = true
